name: CLI Regression Guard

on:
  push:
    paths:
      - "backend/**"
      - "docs/samples/cli_baseline/**"
      - "scripts/check_cli_baseline.py"
      - "backend/tests/**"
      - ".github/workflows/cli-regression.yml"
  pull_request:
    paths:
      - "backend/**"
      - "docs/samples/cli_baseline/**"
      - "scripts/check_cli_baseline.py"
      - "backend/tests/**"

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pydantic psutil pytest

      - name: Run CLI end-to-end tests
        run: pytest backend/tests/test_cli_e2e.py

      - name: Compare CLI output with baselines
        run: python scripts/check_cli_baseline.py
